// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foo.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

#pragma mark - Enum Person_Gender

typedef GPB_ENUM(Person_Gender) {
  Person_Gender_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  Person_Gender_Unknown = 0,
  Person_Gender_Female = 1,
  Person_Gender_Male = 2,
};

GPBEnumDescriptor *Person_Gender_EnumDescriptor(void);

BOOL Person_Gender_IsValidValue(int32_t value);


#pragma mark - FooRoot

@interface FooRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - Person

typedef GPB_ENUM(Person_FieldNumber) {
  Person_FieldNumber_FirstName = 1,
  Person_FieldNumber_LastName = 2,
  Person_FieldNumber_Gender = 3,
};

@interface Person : GPBMessage

@property(nonatomic, readwrite, copy) NSString *firstName;

@property(nonatomic, readwrite, copy) NSString *lastName;

@property(nonatomic, readwrite) Person_Gender gender;

@end

int32_t Person_Gender_RawValue(Person *message);
void SetPerson_Gender_RawValue(Person *message, int32_t value);

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
